on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: TypedocBuild
        uses: erikyo/tsdoc-action@v1
